runtime: python310
entrypoint: gunicorn -b :$PORT aorbo_project.wsgi

env_variables:
  DJANGO_SETTINGS_MODULE: "aorbo_project.settings"

handlers:
  - url: /static
    static_dir: static/
  - url: /.*
    script: auto
